# Generated by Django 4.2.3 on 2023-08-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_education_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Industry',
            new_name='industry',
        ),
    ]
