# Generated by Django 4.2.3 on 2023-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='interface/')),
                ('languageUsed', models.CharField(max_length=300)),
                ('features', models.CharField(max_length=350)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
